### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by kallepersson** [kallepersson/inboxtheme#1]
Please vote on this issue if you want a Firefox version of this extension.

**Comment by JanPokorny** [comment]
Firefox extensions use the same format as Chrome. Firefox's test page tells me that this extension is compatible: https://www.extensiontest.com/test/2f88c5d0-d3ee-11e8-965a-29ce3f6f21ba
Is there any technical obstacle in packaging the extension for Firefox?

**Comment by JanPokorny** [comment]
@kallepersson Does closing mean that there will be a Firefox version?

**Comment by tpai** [comment]
@kallepersson After load into Temporary Add-on of Firefox, it works as expected.

![2019-02-11 12 30 15](https://user-images.githubusercontent.com/579145/52546295-ea722800-2df8-11e9-96bb-ac8a81ef6f54.png)

**Comment by JanPokorny** [comment]
@kallepersson Do you have plans on making the Firefox version? I may try to create the manifest if you don't have the time, as I really want this extension to be on Firefox.

**Comment by ljak** [comment]
Me too. I could give some help if needed (but I need to learn how to dev a Firefox extension!)

**Comment by dan2735** [comment]
Is there any update on a FF version?

**Comment by tpai** [comment]
FF version is here.
https://addons.mozilla.org/en-US/firefox/addon/inbox-theme-for-gmail/

@kallepersson Check this out when you have free time, I uploaded this extension to FF Add-ons and filled the information as you wrote in Chrome extension, if you think this is not ok please let me know I will remove it.

**Comment by enigmaxg2** [comment]
Should be good if it gets a dark version and wallpaper support.

**Comment by lilred** [comment]
I suggest updating the web page at http://flowapps.co/inboxtheme/ with the link to the Firefox version

**Comment by AlecJ** [comment]
Not sure what has changed but noticed recently that the search bar was getting messed up. Would love a fix but understandable if it's not coming.

![Screen Shot 2019-11-19 at 10 07 21 PM](https://user-images.githubusercontent.com/5054790/69205841-1acdbc00-0b19-11ea-9f8b-46a411f71ce5.png)
