### ISSUE TITLE
Toolbar items are too white 

### ISSUE THREAD

**Issue by dru212** [kallepersson/inboxtheme#24]
When you have a message open, you need to be able to use the toolbar buttons up top (archive, snooze, etc.). Currently they are a bit difficult to view against a very light gray background.

If they could either be darkened or create an option to increase the contrast - that would be beneficial to the usability.

**Comment by kallepersson** [comment]
Hi @dru212, could you please share a screenshot of how this looks? This is what is looks like in my browser:

![screen shot 2019-01-30 at 22 11 23](https://user-images.githubusercontent.com/2496/52012868-0104af00-24dc-11e9-909d-9d6e9d988202.png)

**Comment by dru212** [comment]
Sure thing. 

![screenshot-mail google com-2019 01 31-13-42-36](https://user-images.githubusercontent.com/31677159/52087492-75803200-255e-11e9-874d-7cc6d0bf6764.png)

**Comment by kallepersson** [comment]
I think you must have dark theme enabled, please try switching back to the default theme in Gmail Settings -> Themes. Dark Theme will eventually be supported, but it will take some time.

**Comment by dru212** [comment]
Thanks for the tip. While I didn't have the dark theme enabled - I had a background image set. After switching back to the default theme the toolbar buttons look great!
