### ISSUE TITLE
Toolbar changes colors, toolbar text is dark grey

### ISSUE THREAD

**Issue by abrupttranquility** [kallepersson/inboxtheme#25]
![2018-11-15-181824_893x164_scrot](https://user-images.githubusercontent.com/7904551/48570010-84fac200-e903-11e8-809d-f61ff7b4e6e2.png)
![2018-11-15-182215_988x76_scrot](https://user-images.githubusercontent.com/7904551/48570014-875d1c00-e903-11e8-8271-3bf2258bb9b8.png)
The toolbar was grey at first, then changed color after opening and closing an email.
'Gmail' and 'Search mail' font color seems to be too dark to be clearly readable.

**Comment by tpai** [comment]
See https://github.com/kallepersson/inboxtheme/pull/31

**Comment by kallepersson** [comment]
Hi @abrupttranquility, please update and see if this extension persist. This is how it should look on version 1.1.2:

![screen shot 2019-01-30 at 22 11 23](https://user-images.githubusercontent.com/2496/52012909-1974c980-24dc-11e9-883a-65a78bc60579.png)


Thanks!

**Comment by abrupttranquility** [comment]
Works fine now
