### ISSUE TITLE
Top bar does not load with correct color or background-color

### ISSUE THREAD

**Issue by SlowPulseStudios** [kallepersson/inboxtheme#27]
![image](https://user-images.githubusercontent.com/20939260/48799469-12a73900-ed6c-11e8-8ea5-01bfb9571db9.png)

**Comment by tpai** [comment]
See https://github.com/kallepersson/inboxtheme/pull/31

**Comment by kallepersson** [comment]
Hi @SlowPulseStudios , please update and see if this extension persist. This is how it should look on version 1.1.2:

![screen shot 2019-01-30 at 22 11 23](https://user-images.githubusercontent.com/2496/52012909-1974c980-24dc-11e9-883a-65a78bc60579.png)


Thanks!

**Comment by kallepersson** [comment]
Closing, but please reopen if the issue persist.
