### ISSUE TITLE
Trashcan icon does not appear on the right of folded messages

### ISSUE THREAD

**Issue by drakes00** [kallepersson/inboxtheme#29]
Hi,

As mentioned in an issue on playstore, trashcan icon does not appear on the right of folded messages (while archive, delay and mark as new do). This requires to either open the message or to check the box on the left.

![screenshot from 2018-12-04 15-17-27](https://user-images.githubusercontent.com/1948126/49448059-553f2b80-f7d8-11e8-9f1e-a896962b0b5d.png)

Thanks in advance for the help,

**Comment by kallepersson** [comment]
Hi @drakes00! Fair point, will bring it back. Please update to 1.1.3 once published. Thanks!
