### ISSUE TITLE
Unable to use the Gmail setting "Undo Send"

### ISSUE THREAD

**Issue by dru212** [kallepersson/inboxtheme#34]
Having the "Undo Send" feature set to 20 seconds in Gmail and attempting to undo does not appear to work consistently with the inbox theme.

Steps to reproduce:

1. Set Gmail "Undo Send" to 20 seconds
2. Create and Send an email message
3. Clicking on the "Undo" link in the lower left hovering box does not seem to work consistently.  
4. The message sends

Sometimes it does end up working but most of the time it does not. It appears that the Gmail labels underneath the hovering box are interfering with the "Undo" link.

**Comment by tpai** [comment]
Fixed at #35
