### ISSUE TITLE
For me, inboxtheme clobbers gmail's "undo send" feature 

### ISSUE THREAD

**Issue by scerwin** [kallepersson/inboxtheme#54]
After very extensive testing (two tests) on a large number of machines (two) running Windows 10 and up-to-date Chrome, I have found that inboxtheme messes up gmail's handy "undo send" feature. The "undo" button appears for a few seconds but cannot be clicked. The neighboring "view message" button still works, however.

Anyone else: confirm/deny?

**Comment by scerwin** [comment]
Never mind, problem solved: had to turn off chat in gmail's settings. Now undo works.

**Comment by tpai** [comment]
Solved.
